"""Compatibility wrapper exposing deterministic and stochastic wave-space utilities."""

from jax_md.hydro.pse_wave_det import (
    REAL_DTYPE,
    COMPLEX_DTYPE,
    make_reciprocal,
    to_fractional,
    q_grid,
    k_from_q,
    se_alpha,
    hhat_sq_inv,
    choose_theta,
    Hasimoto,
    sinc,
    projector_from_k,
    build_P_modes,
    build_B_modes,
    build_stencils_frac,
    spread,
    gather,
    fft_vec,
    ifft_vec,
    build_Mw_apply,
    Mw_bruteforce,
)
from jax_md.hydro.pse_wave_stoch import (
    build_Mw_sqrt_sampler,
    build_Mw_apply_and_sample,
)

__all__ = [
    'REAL_DTYPE',
    'COMPLEX_DTYPE',
    'make_reciprocal',
    'to_fractional',
    'q_grid',
    'k_from_q',
    'se_alpha',
    'hhat_sq_inv',
    'choose_theta',
    'Hasimoto',
    'sinc',
    'projector_from_k',
    'build_P_modes',
    'build_B_modes',
    'build_stencils_frac',
    'spread',
    'gather',
    'fft_vec',
    'ifft_vec',
    'build_Mw_apply',
    'Mw_bruteforce',
    'build_Mw_sqrt_sampler',
    'build_Mw_apply_and_sample',
]
